---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-demo-io-v1-app
  failurePolicy: Fail
  name: mapp.kb.io
  rules:
  - apiGroups:
    - test.demo.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-demo-io-v1-app
  failurePolicy: Fail
  name: vapp.kb.io
  rules:
  - apiGroups:
    - test.demo.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
  sideEffects: None
